login: &login
  adapter: postgresql
  host: db
  port: 5432
  username: postgres
  password: password

connection: &connection
  encoding: unicode
  pool: 5


development:
  database: publify_dev
  <<: *login
  <<: *connection

test:
  database: publify_tests
  <<: *login
  <<: *connection

production:
  adapter: postgresql
  port: 5432
  encoding: unicode
  pool: 5
  database: publify
  host: database-1.cs3nmjbzzhw5.us-east-1.rds.amazonaws.com
  username: postgres
  password: contrasena
